version: '3.9'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - './mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf'
    restart: unless-stopped
